name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    uses: DustFoundation/shared-actions/.github/workflows/publish-npm.yml@v1.1.1
    secrets:
      npm-publish-token: ${{ secrets.NPM_PUBLISH_TOKEN }}
